/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPortfoliosRouteImport } from './routes/_app/portfolios'
import { Route as AppManageRouteImport } from './routes/_app/manage'
import { Route as AppDashboardsRouteImport } from './routes/_app/dashboards'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppPortfolioPortfolioIdRouteImport } from './routes/_app/portfolio.$portfolioId'
import { Route as AppManagePortfolioIdRouteImport } from './routes/_app/manage.$portfolioId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPortfoliosRoute = AppPortfoliosRouteImport.update({
  id: '/portfolios',
  path: '/portfolios',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppManageRoute = AppManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardsRoute = AppDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPortfolioPortfolioIdRoute = AppPortfolioPortfolioIdRouteImport.update({
  id: '/portfolio/$portfolioId',
  path: '/portfolio/$portfolioId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppManagePortfolioIdRoute = AppManagePortfolioIdRouteImport.update({
  id: '/$portfolioId',
  path: '/$portfolioId',
  getParentRoute: () => AppManageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/about': typeof AppAboutRoute
  '/dashboards': typeof AppDashboardsRoute
  '/manage': typeof AppManageRouteWithChildren
  '/portfolios': typeof AppPortfoliosRoute
  '/profile': typeof AppProfileRoute
  '/': typeof AppIndexRoute
  '/manage/$portfolioId': typeof AppManagePortfolioIdRoute
  '/portfolio/$portfolioId': typeof AppPortfolioPortfolioIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/about': typeof AppAboutRoute
  '/dashboards': typeof AppDashboardsRoute
  '/manage': typeof AppManageRouteWithChildren
  '/portfolios': typeof AppPortfoliosRoute
  '/profile': typeof AppProfileRoute
  '/': typeof AppIndexRoute
  '/manage/$portfolioId': typeof AppManagePortfolioIdRoute
  '/portfolio/$portfolioId': typeof AppPortfolioPortfolioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/dashboards': typeof AppDashboardsRoute
  '/_app/manage': typeof AppManageRouteWithChildren
  '/_app/portfolios': typeof AppPortfoliosRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/': typeof AppIndexRoute
  '/_app/manage/$portfolioId': typeof AppManagePortfolioIdRoute
  '/_app/portfolio/$portfolioId': typeof AppPortfolioPortfolioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/about'
    | '/dashboards'
    | '/manage'
    | '/portfolios'
    | '/profile'
    | '/'
    | '/manage/$portfolioId'
    | '/portfolio/$portfolioId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/about'
    | '/dashboards'
    | '/manage'
    | '/portfolios'
    | '/profile'
    | '/'
    | '/manage/$portfolioId'
    | '/portfolio/$portfolioId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/about'
    | '/_app/dashboards'
    | '/_app/manage'
    | '/_app/portfolios'
    | '/_app/profile'
    | '/_app/'
    | '/_app/manage/$portfolioId'
    | '/_app/portfolio/$portfolioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/portfolios': {
      id: '/_app/portfolios'
      path: '/portfolios'
      fullPath: '/portfolios'
      preLoaderRoute: typeof AppPortfoliosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/manage': {
      id: '/_app/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof AppManageRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboards': {
      id: '/_app/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof AppDashboardsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/portfolio/$portfolioId': {
      id: '/_app/portfolio/$portfolioId'
      path: '/portfolio/$portfolioId'
      fullPath: '/portfolio/$portfolioId'
      preLoaderRoute: typeof AppPortfolioPortfolioIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/manage/$portfolioId': {
      id: '/_app/manage/$portfolioId'
      path: '/$portfolioId'
      fullPath: '/manage/$portfolioId'
      preLoaderRoute: typeof AppManagePortfolioIdRouteImport
      parentRoute: typeof AppManageRoute
    }
  }
}

interface AppManageRouteChildren {
  AppManagePortfolioIdRoute: typeof AppManagePortfolioIdRoute
}

const AppManageRouteChildren: AppManageRouteChildren = {
  AppManagePortfolioIdRoute: AppManagePortfolioIdRoute,
}

const AppManageRouteWithChildren = AppManageRoute._addFileChildren(
  AppManageRouteChildren,
)

interface AppRouteRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppDashboardsRoute: typeof AppDashboardsRoute
  AppManageRoute: typeof AppManageRouteWithChildren
  AppPortfoliosRoute: typeof AppPortfoliosRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPortfolioPortfolioIdRoute: typeof AppPortfolioPortfolioIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppDashboardsRoute: AppDashboardsRoute,
  AppManageRoute: AppManageRouteWithChildren,
  AppPortfoliosRoute: AppPortfoliosRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppPortfolioPortfolioIdRoute: AppPortfolioPortfolioIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
