/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPortfoliosRouteImport } from './routes/_app/portfolios'
import { Route as AppDashboardsRouteImport } from './routes/_app/dashboards'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppManageIndexRouteImport } from './routes/_app/manage/index'
import { Route as AppManagePortfolioPortfolioIdRouteImport } from './routes/_app/manage/portfolio.$portfolioId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPortfoliosRoute = AppPortfoliosRouteImport.update({
  id: '/portfolios',
  path: '/portfolios',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardsRoute = AppDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppManageIndexRoute = AppManageIndexRouteImport.update({
  id: '/manage/',
  path: '/manage/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppManagePortfolioPortfolioIdRoute =
  AppManagePortfolioPortfolioIdRouteImport.update({
    id: '/manage/portfolio/$portfolioId',
    path: '/manage/portfolio/$portfolioId',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/about': typeof AppAboutRoute
  '/dashboards': typeof AppDashboardsRoute
  '/portfolios': typeof AppPortfoliosRoute
  '/profile': typeof AppProfileRoute
  '/': typeof AppIndexRoute
  '/manage': typeof AppManageIndexRoute
  '/manage/portfolio/$portfolioId': typeof AppManagePortfolioPortfolioIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/about': typeof AppAboutRoute
  '/dashboards': typeof AppDashboardsRoute
  '/portfolios': typeof AppPortfoliosRoute
  '/profile': typeof AppProfileRoute
  '/': typeof AppIndexRoute
  '/manage': typeof AppManageIndexRoute
  '/manage/portfolio/$portfolioId': typeof AppManagePortfolioPortfolioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/dashboards': typeof AppDashboardsRoute
  '/_app/portfolios': typeof AppPortfoliosRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/': typeof AppIndexRoute
  '/_app/manage/': typeof AppManageIndexRoute
  '/_app/manage/portfolio/$portfolioId': typeof AppManagePortfolioPortfolioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/about'
    | '/dashboards'
    | '/portfolios'
    | '/profile'
    | '/'
    | '/manage'
    | '/manage/portfolio/$portfolioId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/about'
    | '/dashboards'
    | '/portfolios'
    | '/profile'
    | '/'
    | '/manage'
    | '/manage/portfolio/$portfolioId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/about'
    | '/_app/dashboards'
    | '/_app/portfolios'
    | '/_app/profile'
    | '/_app/'
    | '/_app/manage/'
    | '/_app/manage/portfolio/$portfolioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/portfolios': {
      id: '/_app/portfolios'
      path: '/portfolios'
      fullPath: '/portfolios'
      preLoaderRoute: typeof AppPortfoliosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboards': {
      id: '/_app/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof AppDashboardsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/manage/': {
      id: '/_app/manage/'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof AppManageIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/manage/portfolio/$portfolioId': {
      id: '/_app/manage/portfolio/$portfolioId'
      path: '/manage/portfolio/$portfolioId'
      fullPath: '/manage/portfolio/$portfolioId'
      preLoaderRoute: typeof AppManagePortfolioPortfolioIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppDashboardsRoute: typeof AppDashboardsRoute
  AppPortfoliosRoute: typeof AppPortfoliosRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppManageIndexRoute: typeof AppManageIndexRoute
  AppManagePortfolioPortfolioIdRoute: typeof AppManagePortfolioPortfolioIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppDashboardsRoute: AppDashboardsRoute,
  AppPortfoliosRoute: AppPortfoliosRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppManageIndexRoute: AppManageIndexRoute,
  AppManagePortfolioPortfolioIdRoute: AppManagePortfolioPortfolioIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
